VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemVendor" "Dell"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemProduct" "ENVY dv7"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemVersion" "v1.01"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemSerial" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemSKU" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemFamily" "<empty>"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiSystemUuid" "d18cce0e-44f9-4a74-808c-ff8ff99889da"

VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVendor" "Dell"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiOEMVBoxVer" "Dell v3.1.2"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiOEMVBoxRev" "Dell Rev 1.2.1"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVersion" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBIOSReleaseDate" "12/11/2015"

VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardVendor" "Dell"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardProduct" "Dell Laditude dv7"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardVersion" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardSerial" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardAssetTag" "Random Val"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardLocInChass" "<empty>"
VBoxManage setextradata "Windows10" "VBoxInternal/Devices/pcbios/0/Config/DmiBoardBoardType" "10"